### ISSUE TITLE
Pages not showing on Mobile or Other devices other than main server

### ISSUE THREAD

**Issue by nosizejosh** [2Associes/meteor-boilerplate#56]
Hello And thank you for this starter pack. I am facing a very interesting issue where no page except a blank screen and icon of meteor all things shows on mobile devices when i try to access  a page (running on localhost) via a mobile device.
Interestingly the only pages that show are not found pages ( when i intentionally enter an address to a page that doesnt exist). I have tried to access via http://my.local.ip.addres:3000 as well as https://my.local.ip.addres:3000 and none has worked.

Accessing via another laptop or doesnt work either.  Can you please help? what i'm i doing wrong? @huguesbrunelle  @dvdpearson @andresfloresdev  @marsimeau

**Comment by huguesbrunelle** [comment]
In development mode under iOS, http://localhost:3000 runs as expected. Console returns no error.
On the same WiFi, I try to reach http://xx.x.x.x:3000 and the page is blank. Console returns 3 errors, see attached : 
<img width="1915" alt="screen shot 2019-01-27 at 9 33 30 pm" src="https://user-images.githubusercontent.com/152595/51811520-4d04e900-227b-11e9-95ca-de8bc5dbb7fa.png">

**Comment by marsimeau** [comment]
Hello @nosizejosh @huguesbrunelle,

This seems to be a conflict between dynamic imports and CORS https://github.com/meteor/meteor/issues/10384.

If you still wish to preview your app over local network before this issue is officially fixed on the official Meteor repository, you can downgrade to Meteor 1.6.1 which should work according to the thread above. You could also try disabling CORS or redirect localhost to your host's address on your other devices. While these solutions are certainly not great I can't think of any other way to work around this issue.

Internally we've been doing most of our mobile testing on a staging server so this has not been much an issue.

I'm closing this since there's nothing that can be done on our side at the moment.
